TEST_DURATION_SECONDS = 120

NO_FACE_GRACE_PERIOD = 3
FACE_ALIGNMENT_GRACE_PERIOD = 3
VIOLATION_GRACE_PERIOD = 3

MAX_VIOLATIONS = 2

FACE_MIN_AREA_RATIO = 0.05
FACE_MAX_AREA_RATIO = 0.22

HEAD_CENTER_DEVIATION_THRESHOLD = 0.10
EYE_MOVEMENT_THRESHOLD = 0.35
HEAD_LEFT_DEVIATION_THRESHOLD = 0.20
HEAD_RIGHT_DEVIATION_THRESHOLD = 0.05
